apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
      bali: CP

spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      bali: CP

  template:
    metadata:
      labels:
          bali: CP
    spec:
      containers:
        - name: nginx-container
          image: nginx
        - name: mongo-container
          image: mongo
          
